name: Linters

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: wagoid/commitlint-github-action@v5

      - name: Install packages
        run: npm install

      - name: ESLint
        run: npm run lint:ci

      - name: Prettier
        run: npm run prettier:ci

      - name: Buddy
        run: npm run buddy
